/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/Icon.vue')['default']
    IIcon: typeof import('./src/components/IIcon.vue')['default']
  }
}
